name: Deployment

on:
  pull_request:
    types: [closed]
    branches: 
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm i --global vercel

      - name: Pull
        run: |
          if [ "${{ github.head_ref }}" == "main" ]; then
            vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes
          else
            vercel pull --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --yes
          fi

      - name: Build
        run: |
          if [ "${{ github.head_ref }}" == "main" ]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Deploy
        run: |
          if [ "${{ github.head_ref }}" == "main" ]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi