name: DeploymentProd

on:
  pull_request:
    types: [closed]
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm i --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}